### ISSUE TITLE
darknet2onnx error

### ISSUE THREAD

**Issue by Jeremy-J-J** [MAhaitao999/darknet2onnx#1]
请问darknet yolov3_2_onnx 报错如下：
Traceback (most recent call last):
  File "darknet2onnx.py", line 720, in <module>
    main()
  File "darknet2onnx.py", line 681, in main
    layer_configs = parser.parse_cfg_file(cfg_file_path)
  File "darknet2onnx.py", line 42, in parse_cfg_file
    layer_dict, layer_name, remainder = self._next_layer(remainder)
  File "darknet2onnx.py", line 84, in _next_layer
    layer_param_block, remainder = remainder.split('\n\n', 1)
ValueError: need more than 1 value to unpack
该如何解决呢？

**Comment by MAhaitao999** [comment]
> 请问darknet yolov3_2_onnx 报错如下：
> Traceback (most recent call last):
> File "darknet2onnx.py", line 720, in
> main()
> File "darknet2onnx.py", line 681, in main
> layer_configs = parser.parse_cfg_file(cfg_file_path)
> File "darknet2onnx.py", line 42, in parse_cfg_file
> layer_dict, layer_name, remainder = self._next_layer(remainder)
> File "darknet2onnx.py", line 84, in _next_layer
> layer_param_block, remainder = remainder.split('\n\n', 1)
> ValueError: need more than 1 value to unpack
> 该如何解决呢？

请确定是否是你的配置文件有问题，可以单步调试看一看。

**Comment by ylc2580** [comment]
> 请问darknet yolov3_2_onnx 报错如下：
> Traceback (most recent call last):
> File "darknet2onnx.py", line 720, in
> main()
> File "darknet2onnx.py", line 681, in main
> layer_configs = parser.parse_cfg_file(cfg_file_path)
> File "darknet2onnx.py", line 42, in parse_cfg_file
> layer_dict, layer_name, remainder = self._next_layer(remainder)
> File "darknet2onnx.py", line 84, in _next_layer
> layer_param_block, remainder = remainder.split('\n\n', 1)
> ValueError: need more than 1 value to unpack
> 该如何解决呢？

你好，请问解决了吗。我这边下载作者的原始工程，也是出现这个问题了。

**Comment by ylc2580** [comment]
> > 请问darknet yolov3_2_onnx 报错如下：
> > Traceback (most recent call last):
> > File "darknet2onnx.py", line 720, in
> > main()
> > File "darknet2onnx.py", line 681, in main
> > layer_configs = parser.parse_cfg_file(cfg_file_path)
> > File "darknet2onnx.py", line 42, in parse_cfg_file
> > layer_dict, layer_name, remainder = self._next_layer(remainder)
> > File "darknet2onnx.py", line 84, in _next_layer
> > layer_param_block, remainder = remainder.split('\n\n', 1)
> > ValueError: need more than 1 value to unpack
> > 该如何解决呢？
> 
> 请确定是否是你的配置文件有问题，可以单步调试看一看。

你好，请问你当时的python各种环境是什么呢，我这边下载完咱们的工程直接去运行的话就会报上面的错误

**Comment by MAhaitao999** [comment]
> > > 请问darknet yolov3_2_onnx 报错如下：
> > > Traceback (most recent call last):
> > > File "darknet2onnx.py", line 720, in
> > > main()
> > > File "darknet2onnx.py", line 681, in main
> > > layer_configs = parser.parse_cfg_file(cfg_file_path)
> > > File "darknet2onnx.py", line 42, in parse_cfg_file
> > > layer_dict, layer_name, remainder = self._next_layer(remainder)
> > > File "darknet2onnx.py", line 84, in _next_layer
> > > layer_param_block, remainder = remainder.split('\n\n', 1)
> > > ValueError: need more than 1 value to unpack
> > > 该如何解决呢？
> > 
> > 
> > 请确定是否是你的配置文件有问题，可以单步调试看一看。
> 
> 你好，请问你当时的python各种环境是什么呢，我这边下载完咱们的工程直接去运行的话就会报上面的错误

你好，感谢对本工程的喜欢。之前的测试环境找不到了。我测试了一下我现有的环境可以转成功，你可以按照此环境试一下：
- Ubuntu18.04
- Python3.6.9
- onnx 1.4.1
- numpy 1.19.5

另外这个版本由于Upsample操作对onnx版本有比较大的限制（比较新的onnx不再支持Upsample操作，取而代之的是Resize操作），所以其他版本的请参考我的另一个工程：https://github.com/MAhaitao999/Yolov3_Dynamic_Batch_TensorRT_Triton/blob/master/darknet2onnx/yolov3_to_onnx_with_onnx1_6_0.py

**Comment by ylc2580** [comment]
> > > > 请问darknet yolov3_2_onnx 报错如下：
> > > > Traceback (most recent call last):
> > > > File "darknet2onnx.py", line 720, in
> > > > main()
> > > > File "darknet2onnx.py", line 681, in main
> > > > layer_configs = parser.parse_cfg_file(cfg_file_path)
> > > > File "darknet2onnx.py", line 42, in parse_cfg_file
> > > > layer_dict, layer_name, remainder = self._next_layer(remainder)
> > > > File "darknet2onnx.py", line 84, in _next_layer
> > > > layer_param_block, remainder = remainder.split('\n\n', 1)
> > > > ValueError: need more than 1 value to unpack
> > > > 该如何解决呢？
> > > 
> > > 
> > > 请确定是否是你的配置文件有问题，可以单步调试看一看。
> > 
> > 
> > 你好，请问你当时的python各种环境是什么呢，我这边下载完咱们的工程直接去运行的话就会报上面的错误
> 
> 你好，感谢对本工程的喜欢。之前的测试环境找不到了。我测试了一下我现有的环境可以转成功，你可以按照此环境试一下：
> 
> * Ubuntu18.04
> * Python3.6.9
> * onnx 1.4.1
> * numpy 1.19.5
> 
> 另外这个版本由于Upsample操作对onnx版本有比较大的限制（比较新的onnx不再支持Upsample操作，取而代之的是Resize操作），所以其他版本的请参考我的另一个工程：https://github.com/MAhaitao999/Yolov3_Dynamic_Batch_TensorRT_Triton/blob/master/darknet2onnx/yolov3_to_onnx_with_onnx1_6_0.py

以转tiny为例，我这边对代码的84行进行了替代，改为：
if len(remainder.split('\n\n', 1))==1:
            layer_param_block = remainder.split('\n\n', 1)[0]
            remainder=''
else:
            layer_param_block, remainder = remainder.split('\n\n', 1)
修改之后，可以生成onnx模型，但是onnxruntime运行失败，修改onnx版本为1.4.1之后，onnxruntime也可正常运行。

非常感谢回复，问题已解决。
